### ISSUE TITLE
Support for 1.98

### ISSUE THREAD

**Issue by svenha** [pommi/bonnie2gchart#10]
bonnie2gchart cannot visualize data from the current version 1.98.

**Comment by HobbledGrubs** [comment]
Some example data from 1.98 
1.98,1.98,emu,1,1577916392,12744M,,8192,5,248,99,606642,82,486430,92,346,99,1264615,99,+++++,+++,16,,,,,+++++,+++,+++++,+++,+++++,+++,+++++,+++,+++++,+++,+++++,+++,38763us,85011us,80703us,23903us,2851us,560us,419us,404us,829us,416us,81us,411us
